module.exports ={
    USER_COLLECTION :'USER',
    CATEGORY_COLLECTION :'CATEGORY',
    PRODUCT_COLLECTION :'PRODUCT',
    CART_COLLECTION :'CART',
    ORDER_COLLECTION :'ORDER',
    ADDRESS_COLLECTION :'ADDRESS',
    WISHLIST_COLLECTION : 'WISHLIST',
}